version: '3.4'
services:
  app:
    image: api_node
    container_name: api_node
    build: ./
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
